ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS builder

FROM gcr.io/distroless/static-debian13@sha256:58133991db06659feaabe0f4e97a35cebf15ef4ea08f8a4c6d2ee5f75e4aa6a0
COPY --from=builder /out/grpc /grpc
ENTRYPOINT ["/grpc"]
