ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS builder

FROM gcr.io/distroless/static-debian13@sha256:9197324ba51d9cd071af8505989365c006adf9d6d2067eada25aef00abbb5278
COPY --from=builder /out/openrouter /openrouter
ENTRYPOINT ["/openrouter"]
