// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deepswe_scores.sql

package sqlcgen

import (
	"context"
)

const getScoresByModelIDs = `-- name: GetScoresByModelIDs :many
SELECT model_id, harness, reasoning_effort, pass_rate, pass_at_1, pass_at_4, n_passed, n_attempted, mean_cost_usd, fetched_at FROM deepswe_scores WHERE model_id = ANY($1::text[])
ORDER BY model_id, harness, reasoning_effort
`

func (q *Queries) GetScoresByModelIDs(ctx context.Context, modelIds []string) ([]DeepsweScore, error) {
	rows, err := q.db.Query(ctx, getScoresByModelIDs, modelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeepsweScore
	for rows.Next() {
		var i DeepsweScore
		if err := rows.Scan(
			&i.ModelID,
			&i.Harness,
			&i.ReasoningEffort,
			&i.PassRate,
			&i.PassAt1,
			&i.PassAt4,
			&i.NPassed,
			&i.NAttempted,
			&i.MeanCostUsd,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeepsweScore = `-- name: UpsertDeepsweScore :exec
INSERT INTO deepswe_scores (
    model_id, harness, reasoning_effort, pass_rate, pass_at_1, pass_at_4,
    n_passed, n_attempted, mean_cost_usd, fetched_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (model_id, harness, reasoning_effort) DO UPDATE SET
    pass_rate = EXCLUDED.pass_rate,
    pass_at_1 = EXCLUDED.pass_at_1,
    pass_at_4 = EXCLUDED.pass_at_4,
    n_passed = EXCLUDED.n_passed,
    n_attempted = EXCLUDED.n_attempted,
    mean_cost_usd = EXCLUDED.mean_cost_usd,
    fetched_at = now()
`

type UpsertDeepsweScoreParams struct {
	ModelID         string   `json:"model_id"`
	Harness         string   `json:"harness"`
	ReasoningEffort string   `json:"reasoning_effort"`
	PassRate        *float64 `json:"pass_rate"`
	PassAt1         *float64 `json:"pass_at_1"`
	PassAt4         *float64 `json:"pass_at_4"`
	NPassed         *int64   `json:"n_passed"`
	NAttempted      *int64   `json:"n_attempted"`
	MeanCostUsd     *float64 `json:"mean_cost_usd"`
}

func (q *Queries) UpsertDeepsweScore(ctx context.Context, arg UpsertDeepsweScoreParams) error {
	_, err := q.db.Exec(ctx, upsertDeepsweScore,
		arg.ModelID,
		arg.Harness,
		arg.ReasoningEffort,
		arg.PassRate,
		arg.PassAt1,
		arg.PassAt4,
		arg.NPassed,
		arg.NAttempted,
		arg.MeanCostUsd,
	)
	return err
}
