// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Model struct {
	ID               string             `json:"id"`
	CanonicalSlug    string             `json:"canonical_slug"`
	Name             string             `json:"name"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
	ContextLength    int64              `json:"context_length"`
	CheapestProvider *string            `json:"cheapest_provider"`
	PromptPrice      string             `json:"prompt_price"`
	CompletionPrice  string             `json:"completion_price"`
	Favorite         bool               `json:"favorite"`
	Hidden           bool               `json:"hidden"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TerminalBenchScore struct {
	ModelID               string             `json:"model_id"`
	Leaderboard           string             `json:"leaderboard"`
	Agent                 string             `json:"agent"`
	ReasoningEffort       string             `json:"reasoning_effort"`
	Accuracy              float64            `json:"accuracy"`
	AccuracyCi95HalfWidth float64            `json:"accuracy_ci95_half_width"`
	FetchedAt             pgtype.Timestamptz `json:"fetched_at"`
}
