// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFavoriteIDs = `-- name: ListFavoriteIDs :many
SELECT id FROM models WHERE favorite = TRUE
`

func (q *Queries) ListFavoriteIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listFavoriteIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteModels = `-- name: ListFavoriteModels :many
SELECT id, canonical_slug, name, released_at, context_length, cheapest_provider, prompt_price, completion_price, favorite, hidden, last_seen_at, created_at, updated_at FROM models WHERE favorite = TRUE ORDER BY released_at DESC
`

func (q *Queries) ListFavoriteModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listFavoriteModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalSlug,
			&i.Name,
			&i.ReleasedAt,
			&i.ContextLength,
			&i.CheapestProvider,
			&i.PromptPrice,
			&i.CompletionPrice,
			&i.Favorite,
			&i.Hidden,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHiddenModels = `-- name: ListHiddenModels :many
SELECT id, canonical_slug, name, released_at, context_length, cheapest_provider, prompt_price, completion_price, favorite, hidden, last_seen_at, created_at, updated_at FROM models WHERE hidden = TRUE ORDER BY released_at DESC
`

func (q *Queries) ListHiddenModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listHiddenModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalSlug,
			&i.Name,
			&i.ReleasedAt,
			&i.ContextLength,
			&i.CheapestProvider,
			&i.PromptPrice,
			&i.CompletionPrice,
			&i.Favorite,
			&i.Hidden,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsWithoutScores = `-- name: ListModelsWithoutScores :many
SELECT id, canonical_slug, name, released_at, context_length, cheapest_provider, prompt_price, completion_price, favorite, hidden, last_seen_at, created_at, updated_at FROM models m
WHERE hidden = FALSE
  AND NOT EXISTS (SELECT 1 FROM deepswe_scores s WHERE s.model_id = m.id)
ORDER BY released_at DESC
`

func (q *Queries) ListModelsWithoutScores(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModelsWithoutScores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalSlug,
			&i.Name,
			&i.ReleasedAt,
			&i.ContextLength,
			&i.CheapestProvider,
			&i.PromptPrice,
			&i.CompletionPrice,
			&i.Favorite,
			&i.Hidden,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleModels = `-- name: ListVisibleModels :many
SELECT id, canonical_slug, name, released_at, context_length, cheapest_provider, prompt_price, completion_price, favorite, hidden, last_seen_at, created_at, updated_at FROM models WHERE hidden = FALSE ORDER BY released_at DESC
`

func (q *Queries) ListVisibleModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listVisibleModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalSlug,
			&i.Name,
			&i.ReleasedAt,
			&i.ContextLength,
			&i.CheapestProvider,
			&i.PromptPrice,
			&i.CompletionPrice,
			&i.Favorite,
			&i.Hidden,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFavorite = `-- name: SetFavorite :one
UPDATE models SET favorite = $2, updated_at = now()
WHERE id = $1
RETURNING id, canonical_slug, name, released_at, context_length, cheapest_provider, prompt_price, completion_price, favorite, hidden, last_seen_at, created_at, updated_at
`

type SetFavoriteParams struct {
	ID       string `json:"id"`
	Favorite bool   `json:"favorite"`
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) (Model, error) {
	row := q.db.QueryRow(ctx, setFavorite, arg.ID, arg.Favorite)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.CanonicalSlug,
		&i.Name,
		&i.ReleasedAt,
		&i.ContextLength,
		&i.CheapestProvider,
		&i.PromptPrice,
		&i.CompletionPrice,
		&i.Favorite,
		&i.Hidden,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setHidden = `-- name: SetHidden :one
UPDATE models SET hidden = $2, updated_at = now()
WHERE id = $1
RETURNING id, canonical_slug, name, released_at, context_length, cheapest_provider, prompt_price, completion_price, favorite, hidden, last_seen_at, created_at, updated_at
`

type SetHiddenParams struct {
	ID     string `json:"id"`
	Hidden bool   `json:"hidden"`
}

func (q *Queries) SetHidden(ctx context.Context, arg SetHiddenParams) (Model, error) {
	row := q.db.QueryRow(ctx, setHidden, arg.ID, arg.Hidden)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.CanonicalSlug,
		&i.Name,
		&i.ReleasedAt,
		&i.ContextLength,
		&i.CheapestProvider,
		&i.PromptPrice,
		&i.CompletionPrice,
		&i.Favorite,
		&i.Hidden,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertModel = `-- name: UpsertModel :exec
INSERT INTO models (
    id, canonical_slug, name, released_at, context_length,
    cheapest_provider, prompt_price, completion_price, last_seen_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (id) DO UPDATE SET
    canonical_slug = EXCLUDED.canonical_slug,
    name = EXCLUDED.name,
    released_at = EXCLUDED.released_at,
    context_length = EXCLUDED.context_length,
    cheapest_provider = EXCLUDED.cheapest_provider,
    prompt_price = EXCLUDED.prompt_price,
    completion_price = EXCLUDED.completion_price,
    last_seen_at = now(),
    updated_at = now()
`

type UpsertModelParams struct {
	ID               string             `json:"id"`
	CanonicalSlug    string             `json:"canonical_slug"`
	Name             string             `json:"name"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
	ContextLength    int64              `json:"context_length"`
	CheapestProvider *string            `json:"cheapest_provider"`
	PromptPrice      string             `json:"prompt_price"`
	CompletionPrice  string             `json:"completion_price"`
}

// Never touches favorite/hidden: those are user-controlled flags and must
// survive re-imports from OpenRouter.
func (q *Queries) UpsertModel(ctx context.Context, arg UpsertModelParams) error {
	_, err := q.db.Exec(ctx, upsertModel,
		arg.ID,
		arg.CanonicalSlug,
		arg.Name,
		arg.ReleasedAt,
		arg.ContextLength,
		arg.CheapestProvider,
		arg.PromptPrice,
		arg.CompletionPrice,
	)
	return err
}
