// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeepsweScore struct {
	ModelID         string             `json:"model_id"`
	Harness         string             `json:"harness"`
	ReasoningEffort string             `json:"reasoning_effort"`
	PassRate        *float64           `json:"pass_rate"`
	PassAt1         *float64           `json:"pass_at_1"`
	PassAt4         *float64           `json:"pass_at_4"`
	NPassed         *int64             `json:"n_passed"`
	NAttempted      *int64             `json:"n_attempted"`
	MeanCostUsd     *float64           `json:"mean_cost_usd"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
}

type Model struct {
	ID               string             `json:"id"`
	CanonicalSlug    string             `json:"canonical_slug"`
	Name             string             `json:"name"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
	ContextLength    int64              `json:"context_length"`
	CheapestProvider *string            `json:"cheapest_provider"`
	PromptPrice      string             `json:"prompt_price"`
	CompletionPrice  string             `json:"completion_price"`
	Favorite         bool               `json:"favorite"`
	Hidden           bool               `json:"hidden"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
